
#########################################################################
# WTF Settings file.  Specify settings using yaml format.
# ex:
# login_settings: 
#   login: testuser
#   password: s3cure
#
# Then in your test code, you can refer to it using ConfigReader.
# 
# my_username = WTF_CONFIG_READER.get('login_settings.login')
# my_password = WTF_CONFIG_READER.get('login_settings.password')
# 
#########################################################################

# Settings for Selenium WebDriver used for browser testing.
selenium:
  # Set type to LOCAL for running locally, and to REMOTE, to run on a remote 
  # webdriver.  Default is LOCAL
  type: LOCAL
  #type: REMOTE

  # remote_url is required if type=REMOTE.  Set this to point at the Remote Webdriver 
  # connection string.
  #remote_url: http://localhost:4723/wd/hub

  # Browser can be the following options.
  # ANDROID, CHROME, FIREFOX, HTMLUNIT, HTMLUNITWITHJS, 
  # INTERNETEXPLORER, IPAD, IPHONE, OPERA, SAFARI
  # OTHER - use other for non-browser tests like Appium
  browser: CHROME

  # Required if browser is set to CHROME or FIREFOX.  This should point to the chrome driver path
  # relative to root '/'.
  chromedriver_path: assets/chromedriver.exe
  #firefox_driver: C:/Users/szymonj/virtualenv_frontend/Lib/site-packages/geckodriver.exe

  # Path of Selenium server Jar file.  This is needed for Safari Driver.
  #selenium_server_path: /path/to/selenium-server-standalone-2.37.0.jar

  # Desired capabilities to pass to Selenium Grid.
  # Required if using selenium Grid.
  # desired_capabilities:
    # Target browser version.
    #version: 22

    # ANY, ANDROID, LINUX, MAC, UNIX, VISTA, WIN7, WIN8, WINDOWS, XP
    #platform: ANY
    
  # Terminate Selenium after all tests have run. Disabling this can be helpful
  # during debugging.  In operation you normally want to keep this to clean up 
  # after tests.
  shutdown_hook: true

  # Set to true, to reuse the same browser.  Set to false, to use a fresh browser 
  # instance each time.  Setting it to false is generally better for more consistent 
  # results, but will incur the startup time for the browser to start up for each 
  # test.
  # Default is 'true'
  reusebrowser: true

  # Take screenshot of browser on error.
  take_screenshot: true
  # Take reference screenshot upon encountering a new page.
  take_reference_screenshot: false

  # Multi Process
  # Enabling this setting will spawn a unique webdriver per thread, so no 2 threads
  # share the same webdriver when instantiated using WTF_WEBDRIVER_MANAGER 
  # Default is False
  #threaded: true

web_app:
  #InsysGO stage
  url: http://ipott:ipotttest@www-ipott.stage.insysdev.pl/

login_data:
  #User with with highest package available
  vip_login: pakietvip
  vip_password: demo123

  #User with lower package
  demo_login: pakietdemo
  demo_password: demo123

# Default wait timeout settings. Timeout settings are specified in seconds.
timeout:
  # Timeout for quick things that would normally happen near instantly.
  brief: 1
  # Timeout for something short like a typical ajax response.
  short: 5
  # Timeout for something like loading a large page.
  normal: 10
  # Timeout for something considerably long, such waiting for something to process.
  long: 20
  # Timeout for something extremely long, which a user would normally get 
  # up and take a break.  For example, transcoding an uploaded movie.
  epic: 60


